### ISSUE TITLE
Design Änderung

### ISSUE THREAD

**Issue by FaKo15** [Garados007/Werewolf#11]
Ingame, wenn wir in der Runde sind, ändert sich, wenn ich in die Einstellung gehe, das Design. Es wird zum dem was ich eingestellt habe in den Einstellungen.

![Screenshot (614)](https://user-images.githubusercontent.com/33603179/132105483-fd01ad47-57f4-4fb6-af59-f0fbac05f970.png)

![Screenshot (615)](https://user-images.githubusercontent.com/33603179/132105504-279860c1-e028-449d-9356-acf8bb147ca2.png)

**Comment by Garados007** [comment]
> This is not a bug - it's a feature!

Ja das ist tatsächlich so gewollt, damit man gleich sieht was man dort einstellt. Die Einstellungen, wenn das Menü nicht geöffnet ist, kommen dagegen vom Szenario und können nicht vom Nutzer direkt überschrieben werden.
