### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by FaKo15** [Garados007/Werewolf#2]
Meine Farbe wurde zwar gespeichert, aber wenn ich in die Einstellung gehe ist das Standard-Design wieder da.
![vorher](https://user-images.githubusercontent.com/33603179/131365094-5ebb2f7e-7b11-4a59-9c5b-7ccdae371d2f.png)
![nachher](https://user-images.githubusercontent.com/33603179/131365103-381fb2bd-3809-4903-818c-276057da2122.png)

**Comment by Garados007** [comment]
Ich habe den Fehler gefunden. Dieser wird im nächsten Release behoben sein.
