### ISSUE TITLE
InGame Name

### ISSUE THREAD

**Issue by FaKo15** [Garados007/Werewolf#6]
Wenn man sich anmeldet, dann wird der Name nur in Kleinbuchstaben angezeigt und ebenso bei Keycloak gespeichert. Trotz änderung in Keycloak bleibt das Probelm. Leute die sich einen Gast-Account anlegen, können auch Namen mit Großbuchstaben eingeben, die so auch angezeigt werden. 

![image](https://user-images.githubusercontent.com/33603179/132029571-da21e2ac-964f-471b-a65a-9adfe8392592.png)

**Comment by Garados007** [comment]
Dieses Ticket hängt mit #4 zusammen. Auf seitens Werwolf ist jetzt alles durch #7 geregelt. Doch leider gibt es noch keinen Editor seitens Keycloak für diese Angaben.
Der Übersichtlichkeit halber wird dieses Ticket geschlossen und der weitere Fortschritt wird in #4 verfolgt.
